### ISSUE TITLE
404 missing link on home page

### ISSUE THREAD

**Issue by gsoumilas** [enosysau/WEBSITE#14]
Hi Guys,
the contact button doe snot go to the contact form for the following button:

"Find out more" in Enosys Solutions Awarded the Palo Alto Networks APAC Excellence in Professional Services for 2017.

**Comment by enosysau** [comment]
@gsoumilas can you provide me the link to the page in question

**Comment by enosysau** [comment]
Found it! 

> https://enosys.com.au/full-width.html
