### ISSUE TITLE
404 missing link on staff augmentation page

### ISSUE THREAD

**Issue by amanuelw** [enosysau/WEBSITE#17]
Drop down menu on Home Page > Services > Staff Augmentation leads to error 404

**Comment by enosysau** [comment]
:(
``
[simonsigre@simonlaptop WEBSITE]$ grep -ri "services7" * | awk '{print $1}'| sort | uniq | wc -l
79
``

**Comment by enosysau** [comment]
Fixed

> [simonsigre@simonlaptop WEBSITE]$ find . -name "*.html" -exec sed -i "s/services7/staffaugmentation/g" '{}' \;
[simonsigre@simonlaptop WEBSITE]$ grep -r "services7" * | awk '{print $1}'| sort | uniq | wc -l
0
