### ISSUE TITLE
404 missing link on staff technical services page

### ISSUE THREAD

**Issue by amanuelw** [enosysau/WEBSITE#18]

**Comment by enosysau** [comment]
> [simonsigre@simonlaptop WEBSITE]$ grep -r "services11" * | awk '{print $1}'| sort | uniq | wc -l
79

**Comment by enosysau** [comment]
@amanuelw  just confirming, do you mean the "technical support" references or is there a "technical services" that I am missing?

**Comment by enosysau** [comment]
I'm going to assume yes.

> [simonsigre@simonlaptop WEBSITE]$ find . -name "*.html" -exec sed -i "s/services8/techsupport/g" '{}' \;
[simonsigre@simonlaptop WEBSITE]$ grep -r "services8" * | awk '{print $1}'| sort | uniq | wc -l
0

**Comment by amanuelw** [comment]
@simonsigre sorry, I meant "Techincal Support"
